[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49986
Protocol = 'http'
StartupMsg = 'REST device started'
Timeout = 5000
ConnectRetries = 20
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Driver configs
[Driver]

# Pre-define Devices
[[DeviceList]]
  Name = 'sample-json'
  Profile = 'sample-json'
  Description = 'RESTful Device that sends in JSON data'
  Labels = [ 'rest', 'json' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = 'sample-image'
  Profile = 'sample-image'
  Description = 'RESTful Device that sends in binary image data'
  Labels = [ 'rest', 'binary', 'image' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = 'sample-numeric'
  Profile = 'sample-numeric'
  Description = 'RESTful Device that sends in numeric data'
  Labels = [ 'rest', 'numeric', 'float', 'int' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
